### ISSUE TITLE
Package all data to create competition

### ISSUE THREAD

**Issue by danielhers** [cfmrp/codalab#1]
I wrote https://github.com/cfmrp/codalab/blob/master/Makefile to package all data for the competition to upload to CodaLab, but it currently relies on our internal makefiles. To work, we'll need to

1. Remove the `scp` command from the `release` target
2. Add a target for the gold evaluation graphs

@oepen

**Comment by oepen** [comment]
i just added 'evaluation09.tgz' into SVN tracking, and changed 'evaluation/Makefile' to include the gold-standard target graphs in the archive.

in general, i snapshot releases that we make to participants (or the LDC) in SVN and would recommend just using the archives from SVN (rather than re-generating them; which could in principle result in subtle or obscure differences, for example because the software has evolved).

but do we actually need the training or companion data in CodaLab?

**Comment by danielhers** [comment]
We're just doing validation on CodaLab so this is not necessary.
